## **Programming Assignment 2**
#### Numerical Python (NumPy)
#### ----------------------------------------------------------------------------------------------------------

#### **01 Normalization Problem**

In [30]:
# to access NumPy library
import numpy as np 

# generates random 5x5 ndarray in variable 
X = np.random.random((5,5))

In [31]:
# normalize the ndaaray using the formula
mean = X.mean() # calculates the mean
std = X.std() # calculates the standard deviation

# formula
X_normalized = (X - mean) / std 

In [32]:
# saving the noramlized ndarray data as 'X_normalized.npy'
np.save('X_normalized.npy', X_normalized)

# display a successful message
print("The normalized NumPy array has been saved as ‘X_normalized.npy’.")

The normalized NumPy array has been saved as ‘X_normalized.npy’.


In [33]:
# display the normalized NumPY (ndarray)
data = np.load('X_normalized.npy')
data

array([[-1.68724094,  1.0836355 ,  0.8330781 ,  0.5255478 ,  0.23513261],
       [-0.78314911,  0.96494151,  1.3862755 , -0.29981152,  1.08544036],
       [-0.25330901, -0.38491966, -1.50472513, -0.86494597,  1.15939421],
       [ 1.30963222, -1.73095719,  1.21152323,  0.4372095 , -1.46126755],
       [ 0.06752432, -0.82993508,  0.3554339 ,  0.26555233, -1.12005994]])

####

#### **02 Division by 3 Problem**

In [43]:
# to access NumPy library
import numpy as np 

# generates a 10x10 ndarray with squares of the first 100 positive integers
squares = np.arange(1, 101)**2
squares_reshape = squares.reshape(10, 10)

In [44]:
# display the 10x10 array
print("10x10 ndarray of squares of first 100 positive integers:")
print(squares_reshape)

10x10 ndarray of squares of first 100 positive integers:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [45]:
# find for the elements in the ndarray that are divisible by 3
div_by_3 = squares_reshape[squares_reshape % 3 == 0]

In [37]:
# store the elements that are divisible by 3 to a file named 'div_by_3.npy'
np.save('div_by_3.npy', div_by_3)

In [47]:
# display a successful message
print("The elements that are divisible by 3 has been saved as ‘div_by_3.npy’.")

The elements that are divisible by 3 has been saved as ‘div_by_3.npy’.


In [48]:
# display the elements
data = np.load('div_by_3.npy')
data

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])